title: Sunny Snail
email: liyantong14@gmail.com
description: Stay hungry, stay foolish, stay young, stay explore.
 
baseurl: https://alext1.github.io/
url: ""
twitter_username: AlexTong
github_username:  AlexT1

# Build settings
markdown: kramdown
#theme: minima
remote_theme: benbalter/retlab
plugins:
  - jekyll-feed
